### ISSUE TITLE
Cannot authenticate to container registry

### ISSUE THREAD

**Issue by MJECloud** [tfenster/BCinaB#7]
Hey Tobias, 

can you add an option to login to a registry?
For example when i try to pull an insider Image it will fail because docker cant authenticate. 

![image](https://user-images.githubusercontent.com/22131101/50677073-1e874b80-0ff8-11e9-98d8-951ff4357408.png)

Thank you!
 
Greetings,
Maurice

**Comment by tfenster** [comment]
Good idea. As a workaround for now: If you do a docker login on the host, BCinaB should also be able to pull

**Comment by MJECloud** [comment]
Thanks for your quick repsonse. 
I tried that but i got the same error again. 
![image](https://user-images.githubusercontent.com/22131101/50681693-b42cd600-100c-11e9-85a1-d784f933d81d.png)

When i try to pull it manually i got no errors. 
![image](https://user-images.githubusercontent.com/22131101/50681751-e3dbde00-100c-11e9-900c-fa199fdf55ff.png)

**Comment by tfenster** [comment]
Hm, not sure what I tested earlier but it no longer works for me as well. Will have to dig a bit deeper

**Comment by tfenster** [comment]
Ok, I implemented a quick and ugly workaround that I don't want to "officially" push, but could you open your docker-compose.yml and replace `arssolvendi.azurecr.io/bcinab-api:patch4` with `arssolvendi.azurecr.io/bcinab-api:mjeclod`, do a `docker-compose up` again so that it pulls and starts the new version and then try again to pull from bcinsider? I'd like to make sure that this works not only for me before actually implementing it

**Comment by MJECloud** [comment]
It seems to work. 
Thank you!

**Comment by tfenster** [comment]
Sorry, didn't make it in alpha5

**Comment by tfenster** [comment]
Will be there in alpha6. You get a little key button in the top right and if you click on it, you can set credentials. Any pull for that registry will then use those credentials
